-- ============================================================================
--  V10 — оформление заказа маркетплейса (корзина + ПВЗ СДЭК).
--    Снапшот чекаута сохраняется в момент создания платежа, чтобы асинхронный
--    вебхук Юкассы мог собрать заказ (Order + позиции) без контекста запроса.
--    payment_transaction      — новые nullable-колонки: клиент + адрес ПВЗ;
--    payment_transaction_item — позиции корзины (цена в копейках — снимок на момент оплаты).
-- ============================================================================

ALTER TABLE payment_transaction
    ADD COLUMN customer_name  VARCHAR(255),
    ADD COLUMN customer_phone VARCHAR(64),
    ADD COLUMN pvz_city       VARCHAR(255),
    ADD COLUMN pvz_street     VARCHAR(512),
    ADD COLUMN pvz_code       VARCHAR(64);

CREATE TABLE payment_transaction_item (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id UUID         NOT NULL REFERENCES payment_transaction (id) ON DELETE CASCADE,
    product_id     UUID,
    product_name   VARCHAR(255) NOT NULL,
    price_kopecks  BIGINT       NOT NULL,
    quantity       INTEGER      NOT NULL
);

CREATE INDEX idx_payment_transaction_item_tx ON payment_transaction_item (transaction_id);
