-- ============================================================================
--  V7 — кастомные позиции под-заказа (custom products) внутри сделки + их файлы.
--  Самостоятельная производственная сущность под Order; amoCRM её не трогает
--  (в отличие от order_items, которые перетираются при синхронизации).
-- ============================================================================

CREATE TABLE custom_product_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT       NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    product_name VARCHAR(255) NOT NULL,
    description  TEXT,
    quantity     INTEGER      NOT NULL,
    status       VARCHAR(32)  NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP
);

CREATE INDEX idx_custom_product_items_order_id ON custom_product_items (order_id);

-- Файлы позиции: каждая строка — отдельный файл со своим id (поштучное удаление).
CREATE TABLE custom_product_files (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id    BIGINT       NOT NULL REFERENCES custom_product_items (id) ON DELETE CASCADE,
    s3_key     VARCHAR(512) NOT NULL,
    filename   VARCHAR(255),
    created_at TIMESTAMP    NOT NULL
);

CREATE INDEX idx_custom_product_files_item_id ON custom_product_files (item_id);
